export const BUTTON_CLICKED_REQUEST = 'BUTTON_CLICKED_REQUEST';
export const BUTTON_CLICKED_SUCCESS = 'BUTTON_CLICKED_SUCCESS';
export const BUTTON_CLICKED_FAILURE = 'BUTTON_CLICKED_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
